### ISSUE TITLE
required properties for render: type & docs

### ISSUE THREAD

**Issue by cainlevy** [bustle/mobiledoc-vdom-renderer#6]
The render method accepts options with four properties. Three appear to be required (render will throw an error if they are missing) and one has a default.

1) the [`interface Options`](https://github.com/bustle/mobiledoc-vdom-renderer/blob/master/index.ts#L16-L21) type indicates that all four are required
2) the README example only shows one property under ["Usage"](https://github.com/bustle/mobiledoc-vdom-renderer#usage) and indicates that it is the only required one in the [API doc](https://github.com/bustle/mobiledoc-vdom-renderer#options-required)

**Comment by dtetto** [comment]
Thanks for catching all these.

The intended behavior is that only `createElement` is required. `getCardComponent` and `getAtomComponent` throw *if* the Mobiledoc has cards or atoms respectively: e.g., we do not [yet?] use atoms at Bustle, so do not need to specify the latter. Any thoughts on whether it would be better/clearer to default to a no-op rather than throwing an error?

(In the meantime, I’ll fix up the `Options` interface accordingly.)
